app/src/blueprints/game_bp/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.simple import HiddenField


class AnswerForm(FlaskForm):
    csrf_token = HiddenField()

app/src/blueprints/game_bp/__init__.py
from flask import Blueprint

game_bp = Blueprint('game_bp', __name__, template_folder='templates')

from . import routes

app/src/blueprints/game_bp/routes.py
import time
from pathlib import Path

from flask import session, render_template, redirect, url_for, request, flash, jsonify

from app.src.blueprints.game_bp.forms import AnswerForm
from app.src.database.repository import Repository
from app.src.blueprints.game_bp import game_bp
from app.src.services.game_service import GameService

repository = Repository()
game_service = GameService()

@game_bp.route('/game/loading')
def game_loading():
    return render_template('loading.html')

@game_bp.route('/game/new/start')  # генерация новой игры через AJAX - чтобы отображать загрузочную анимацию
def start_new_game():
    if 'user_id' in session:
        user_id = session['user_id']
        game_service.generate_new_game()
        return jsonify({'status': 'success', 'redirect': url_for('game_bp.game_question')})
    return jsonify({'status': 'error', 'redirect': url_for('auth_bp.signin')})

@game_bp.route('/game/new')  # Редирект на страницу загрузки
def new_game():
    return redirect(url_for('game_bp.game_loading'))

@game_bp.route('/game/question')
def game_question(): # редирект если пользователь не авторизован
    if 'user_id' not in session:
        return jsonify({'status': 'error', 'redirect': url_for('auth_bp.signin')})
    card_id = game_service.get_current_card()
    BASE_DIR = Path(__file__).resolve().parents[3]
    # USER_DATA_DIR = BASE_DIR / 'static/user_data'
    image_url = url_for('user_data', filename=f"{card_id}.jpg")
    if card_id:
        return render_template('gamecards.html', image_path=image_url)
    else:
        return redirect(url_for('game_bp.game_result'))

@game_bp.route('/game/answer', methods=['POST'])
def game_answer():
    # эндпоинт взаимодействует с фронтендом через AJAX
    # при взаимодействии через формы возникает проблема с отображением того правильно пользователь ответил или нет
    print(request.data)
    data = request.get_json()
    user_answer = data.get('answer')
    is_correct = game_service.check_answer(user_answer)
    response = {
        "message": "Правильно!" if is_correct else "Неправильно!",
        "is_correct": is_correct
    }
    return jsonify(response), 200

@game_bp.route('/game/result')
def game_result():
    correct = session.get('correct_answers', 0)
    incorrect = len(session.get('game_cards')) - correct
    total_questions = len(session.get('game_cards'))
    if 'user_id' in session: # редирект если пользователь не авторизован
        user_id = session['user_id']
        rating, rating_new = game_service.update_rating(correct, incorrect, total_questions, user_id)
        return render_template('result.html', correct=correct, incorrect=incorrect, total_questions=total_questions, rating_new=rating_new, rating=rating)
    return jsonify({'status': 'error', 'redirect': url_for('auth_bp.signin')})

app/src/blueprints/game_bp/templates/gamecards.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5 d-flex justify-content-center">
        <div class="card shadow-lg" style="max-width: 700px; width: 100%;">
            <div class="card-header bg-primary text-white text-center">
                <h2>Реальное изображение или ИИ?</h2>
            </div>
            <div class="card-body text-center">
            <img id="game-image" src="{{ image_path }}" alt="Изображение" class="img-fluid mb-3" style="width: 70%; height: auto;">
                <div class="alert d-none" id="result-message" role="alert"></div>
                <div class="d-flex" style="gap: 5px">
                    <button class="btn btn-success" style="width: 100%; margin: 5px" onclick="sendAnswer('REAL')">Реальное</button>
                    <button class="btn btn-danger" style="width: 100%; margin: 5px" onclick="sendAnswer('AI')">ИИ</button>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
    function sendAnswer(answer) {
        const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');  // Получаем CSRF-токен

        fetch("{{ url_for('game_bp.game_answer') }}", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRF-Token": csrfToken
            },
            body: JSON.stringify({ answer: answer })  // Отправляем ответ как JSON
        })
        .then(response => {
            if (!response.ok) {
                throw new Error("Ошибка сервера: " + response.status);
            }
            return response.json();
        })
        .then(data => {
            const messageBox = document.getElementById("result-message");
            messageBox.classList.remove("d-none", "alert-success", "alert-danger");
            messageBox.textContent = data.message;
            messageBox.classList.add(data.is_correct ? "alert-success" : "alert-danger");

            setTimeout(() => {
                window.location.href = "{{ url_for('game_bp.game_question') }}";
            }, 1500);
        })
        .catch(error => {
            alert("Ошибка при отправке ответа: " + error.message);
        });
    }
    </script>
{% endblock %}

app/src/blueprints/game_bp/templates/loading.html
{% extends 'base.html' %}
{% block content %}
    <div class="d-flex justify-content-center align-items-center vh-100">
    <div class="text-center">
        <div class="spinner-border text-primary" role="status">
            <span class="visually-hidden">Загрузка...</span>
        </div>
        <div id="loading-text" class="text-primary mt-2">Игра загружается...</div>
    </div>
    </div>
    <script>
        function startGame() {
            fetch("{{ url_for('game_bp.start_new_game') }}")
                .then(response => response.json())
                .then(data => {
                    if (data.status === 'success') {
                        window.location.href = data.redirect;
                    } else {
                        alert('Ошибка! Перенаправление на страницу входа.');
                        window.location.href = data.redirect;
                    }
                })
                .catch(() => {
                    alert('Ошибка при запуске игры.');
                });
        }
        startGame();
    </script>
{% endblock %}

app/src/blueprints/game_bp/templates/result.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5 d-flex justify-content-center">
        <div class="card shadow-lg" style="max-width: 600px; width: 100%;">
            <div class="card-header bg-primary text-white text-center">
                <h2>Результаты игры</h2>
            </div>
            <div class="card-body text-center">
                <p class="fs-4">Всего вопросов: <span class="fw-bold">{{ total_questions }}</span></p>
                <p class="fs-4 text-success">Правильных ответов: <span class="fw-bold">{{ correct }}</span></p>
                <p class="fs-4 text-danger">Неправильных ответов: <span class="fw-bold">{{ total_questions - correct}}</span></p>
                <p class="fs-4 text-primary">Рейтинг: <span class="fw-bold">{{ rating_new }} (изменился на {{ rating_new - rating}})</span></p>
            </div>
            <div class="card-footer text-center">
                <a href="{{ url_for('game_bp.new_game') }}" class="btn btn-primary">Играть снова</a>
                <a href="{{ url_for('home_bp.home') }}" class="btn btn-secondary">На главную</a>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}