app/src/blueprints/auth_bp/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.simple import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, EqualTo


class LoginForm(FlaskForm):
    login = StringField('Логин', validators=[InputRequired(), Length(min=3, max=20)])
    password = PasswordField('Пароль', validators=[InputRequired(), Length(min=6, max=30)])
    submit = SubmitField('Войти')

class RegisterForm(FlaskForm):
    username = StringField('Придумайте логин', validators=[
        InputRequired(), Length(min=3, max=30)
    ])
    password = PasswordField('Пароль', validators=[
        InputRequired(), Length(min=6)
    ])
    confirm_password = PasswordField('Повторите пароль', validators=[
        InputRequired(), EqualTo('password', message='Пароли должны совпадать')
    ])
    submit = SubmitField('Зарегистрироваться')

app/src/blueprints/auth_bp/__init__.py
from flask import Blueprint

auth_bp = Blueprint('auth_bp', __name__, template_folder='templates')

from . import routes

app/src/blueprints/auth_bp/routes.py
from flask import render_template, flash, session, redirect, url_for

from . import auth_bp
from app.src.blueprints.auth_bp.forms import LoginForm, RegisterForm
from app.src.database.repository import Repository

repository = Repository()

@auth_bp.route('/signin', methods=['GET', 'POST'])
def signin():
    form = LoginForm()
    if form.validate_on_submit():
        login = form.login.data
        password = form.password.data
        user = repository.get_user(login, password)
        if user:
            session['user_id'] = user.id
            return redirect(url_for('home_bp.home'))
        else:
            pass
    return render_template('signin.html', form=form)

@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        res = repository.add_user(username, password)
        if not res:
            flash('Пользователь с таким логином уже существует', 'danger')
        # return redirect(url_for('login'))
        user = repository.get_user(username, password)
        if user:
            session['user_id'] = user.id
            return redirect(url_for('home_bp.home'))
    return render_template('signup.html', form=form)

@auth_bp.route('/logout')
def logout():
    session.clear()
    flash("Вы вышли из аккаунта", "info")
    return redirect(url_for('auth_bp.signin'))

app/src/blueprints/auth_bp/templates/signin.html
{% extends 'base.html' %}
{% block content %}
<body class="bg-light">
  <div class="d-flex justify-content-center align-items-center min-vh-100">
    <div class="container" style="max-width: 400px;">
      <h2 class="text-center mb-4">Вход</h2>

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <div class="alert alert-warning">
            {% for msg in messages %}
              <div>{{ msg }}</div>
            {% endfor %}
          </div>
        {% endif %}
      {% endwith %}

    <form method="post">
      <div>{{ form.hidden_tag() }}</div>
      <div class="mb-3">
        {{ form.login.label(class="form-label") }}
        {{ form.login(class="form-control") }}
      </div>

      <div class="mb-3">
        {{ form.password.label(class="form-label") }}
        {{ form.password(class="form-control") }}
      </div>

      {{ form.submit(class="btn btn-primary w-100") }}
    </form>

      <div class="mt-3 text-center">
        <a href="{{ url_for('auth_bp.signup') }}">Нет аккаунта? Зарегистрируйтесь</a>
      </div>
    </div>
  </div>
</body>
{% endblock %}

app/src/blueprints/auth_bp/templates/signup.html
{% extends 'base.html' %}
{% block content %}
  <div class="d-flex justify-content-center align-items-center min-vh-100">
    <div class="container" style="max-width: 400px;">
      <h2 class="text-center mb-4">Регистрация</h2>

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <div class="alert alert-warning">
            {% for msg in messages %}
              <div>{{ msg }}</div>
            {% endfor %}
          </div>
        {% endif %}
      {% endwith %}

      <form method="post">
        {{ form.hidden_tag() }}

        <div class="mb-3">
          {{ form.username.label(class="form-label") }}
          {{ form.username(class="form-control") }}
          {% for error in form.username.errors %}
            <div class="text-danger">{{ error }}</div>
          {% endfor %}
        </div>

        <div class="mb-3">
          {{ form.password.label(class="form-label") }}
          {{ form.password(class="form-control") }}
          {% for error in form.password.errors %}
            <div class="text-danger">{{ error }}</div>
          {% endfor %}
        </div>

        <div class="mb-3">
          {{ form.confirm_password.label(class="form-label") }}
          {{ form.confirm_password(class="form-control") }}
          {% for error in form.confirm_password.errors %}
            <div class="text-danger">{{ error }}</div>
          {% endfor %}
        </div>

        {{ form.submit(class="btn btn-primary w-100") }}
      </form>

      <div class="mt-3 text-center">
        <a href="{{ url_for('auth_bp.signin') }}">Уже есть аккаунт? Войдите</a>
      </div>
    </div>
  </div>
{% endblock %}